name: riverpod_zero_hero_thecmmbay
description: "Demo app for my talk on Riverpod for The Community Bay"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  riverpod_annotation: ^2.3.5
  universal_platform: ^1.1.0
  url_launcher: ^6.3.0
  window_manager: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/layer/
    - assets/layer/condimento/
    - assets/layer/impasto/
    - assets/layer/salsa/
