name: riverpod_zero_hero_thecmmbay
description: "Demo app for my talk on Riverpod for The Community Bay"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  universal_platform: ^1.1.0
  window_manager: ^0.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
